username="pratima101"
print(id(username))
username="pratima102"
print(id(username))
account_no1=122121
print(id(account_no1))
account_no2=122121
print(id(account_no2))
cart=['apples','bananas']
cart.append('chips')
print(cart)
s={1,2,3,4}
s.add(3)
s.add(6)
s.add(5)
print(s)
a={'a','d','c'}
print(hash('b'))
a.add('b')
a.add('b')
print(a)
print(hash('a'))
print(type(a))
ar=dict()
print(type(ar))
user={'username':'pratima101','pwd':'sri123'}
print(user)
user['username']='pratima102'
print(user)
